apiVersion: v1 
kind: Service
metadata:
  name: iweb-service
spec:
  type: NodePort
  selector:
    app: iweb  
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000
